import { cp, copyFile, mkdir, readFile, rm, writeFile } from 'node:fs/promises'
import { existsSync } from 'node:fs'
import path from 'node:path'
import { spawn } from 'node:child_process'
import { fileURLToPath, pathToFileURL } from 'node:url'
import {
  PROJECT_ROOT,
  formatErrors,
  isHttpsUrl,
  resolveLocalResource,
  validateConfigFile
} from './lib/config.mjs'

const sourceEntries = [
  '.gitignore',
  'README.md',
  'README_EN.md',
  'CHANGELOG.md',
  'LICENSE',
  'SECURITY.md',
  'CONTRIBUTING.md',
  'package.json',
  'package-lock.json',
  'rspack.config.js',
  'customize.schema.json',
  'index.html',
  'script',
  'style',
  'img',
  'music',
  'fonts',
  'scripts'
]

function parseArguments(argumentsList) {
  const values = {}
  for (let index = 0; index < argumentsList.length; index += 1) {
    const argument = argumentsList[index]
    if (argument === '--config' || argument === '--output') {
      values[argument.slice(2)] = argumentsList[index + 1]
      index += 1
    }
  }
  if (!values.config) throw new Error('Usage: npm run create -- --config <file> [--output <directory>]')
  return values
}

function slugify(value) {
  const slug = String(value || 'birthday')
    .normalize('NFKD')
    .replace(/[^\p{L}\p{N}]+/gu, '-')
    .replace(/^-+|-+$/g, '')
    .toLowerCase()
  return slug || 'birthday'
}

function sanitizedFilename(source, usedNames) {
  const extension = path.extname(source).toLowerCase()
  const stem = path.basename(source, extension)
    .normalize('NFKD')
    .replace(/[^\p{L}\p{N}._-]+/gu, '-')
    .replace(/^-+|-+$/g, '') || 'asset'
  let candidate = `${stem}${extension}`
  let suffix = 2
  while (usedNames.has(candidate.toLowerCase())) {
    candidate = `${stem}-${suffix}${extension}`
    suffix += 1
  }
  usedNames.add(candidate.toLowerCase())
  return candidate
}

function isWithin(child, parent) {
  const relative = path.relative(parent, child)
  return relative === '' || (!relative.startsWith(`..${path.sep}`) && relative !== '..' && !path.isAbsolute(relative))
}

async function copySource(outputDirectory) {
  for (const entry of sourceEntries) {
    const source = path.join(PROJECT_ROOT, entry)
    if (existsSync(source)) await cp(source, path.join(outputDirectory, entry), { recursive: true })
  }
}

async function copyResource(value, configDirectory, outputDirectory, usedNames) {
  if (!value || isHttpsUrl(value)) return value
  const source = resolveLocalResource(value, configDirectory)
  if (!source) return value

  if (isWithin(source, PROJECT_ROOT)) {
    return path.relative(PROJECT_ROOT, source).split(path.sep).join('/')
  }

  const destinationDirectory = path.join(outputDirectory, 'assets', 'user')
  await mkdir(destinationDirectory, { recursive: true })
  const filename = sanitizedFilename(source, usedNames)
  await copyFile(source, path.join(destinationDirectory, filename))
  return `assets/user/${filename}`
}

async function copyConfiguredResources(config, configDirectory, outputDirectory) {
  const result = structuredClone(config)
  const usedNames = new Set()
  result.theme = result.theme || 'classic'
  result.imagePath = await copyResource(result.imagePath, configDirectory, outputDirectory, usedNames)
  result.music = await copyResource(result.music, configDirectory, outputDirectory, usedNames)

  if (Array.isArray(result.fonts)) {
    result.fonts = await Promise.all(result.fonts.map(async (font) => ({
      ...font,
      path: await copyResource(font.path, configDirectory, outputDirectory, usedNames)
    })))
  }
  return result
}

function run(command, argumentsList, options) {
  return new Promise((resolve, reject) => {
    const child = spawn(command, argumentsList, { ...options, stdio: 'inherit' })
    child.on('error', reject)
    child.on('exit', (code) => {
      if (code === 0) resolve()
      else reject(new Error(`Build failed with exit code ${code}`))
    })
  })
}

async function buildGeneratedSite(outputDirectory) {
  const cliPath = path.join(PROJECT_ROOT, 'node_modules', '@rspack', 'cli', 'bin', 'rspack.js')
  if (!existsSync(cliPath)) throw new Error('Rspack is not installed. Run npm ci before creating a site.')
  await run(process.execPath, [cliPath, 'build'], {
    cwd: outputDirectory,
    env: {
      ...process.env,
      NODE_PATH: path.join(PROJECT_ROOT, 'node_modules'),
      HAPPY_BIRTHDAY_SHARED_NODE_MODULES: path.join(PROJECT_ROOT, 'node_modules')
    }
  })
}

function generatedReadme(config) {
  const displayName = config.name || 'your recipient'
  return `# Birthday site for ${displayName}\n\nThis directory was generated by HappyBirthday. Edit \`customize.json\`, then run \`npm ci\` and \`npm run build\`. Deploy the generated \`dist/\` directory to any static host.\n\nNo credentials, deployment settings, or telemetry are included.\n`
}

export async function createSite({ configPath, outputDirectory } = {}) {
  if (!configPath) throw new Error('A configuration file is required')
  const validation = await validateConfigFile(configPath)
  if (validation.errors.length > 0) throw new Error(`Invalid configuration:\n${formatErrors(validation.errors)}`)

  const defaultOutput = path.join(PROJECT_ROOT, 'generated', `${slugify(validation.config.name)}-birthday`)
  const output = path.resolve(outputDirectory || defaultOutput)
  const generatedRoot = path.join(PROJECT_ROOT, 'generated')

  if (existsSync(output)) throw new Error(`Refusing to overwrite existing directory: ${output}`)
  if (isWithin(output, PROJECT_ROOT) && !isWithin(output, generatedRoot)) {
    throw new Error('Output inside this repository must be placed under generated/')
  }

  await mkdir(output, { recursive: false })
  try {
    await copySource(output)
    const configured = await copyConfiguredResources(validation.config, path.dirname(validation.configPath), output)
    await writeFile(path.join(output, 'customize.json'), `${JSON.stringify(configured, null, 2)}\n`)
    await writeFile(path.join(output, 'GENERATED.md'), generatedReadme(configured))
    await buildGeneratedSite(output)
    return { outputDirectory: output, config: configured }
  } catch (error) {
    await rm(output, { recursive: true, force: true })
    throw error
  }
}

export async function createCommand(argumentsList = process.argv.slice(2)) {
  const values = parseArguments(argumentsList)
  return createSite({ configPath: path.resolve(values.config), outputDirectory: values.output && path.resolve(values.output) })
}

if (process.argv[1] && import.meta.url === pathToFileURL(path.resolve(process.argv[1])).href) {
  createCommand().then(({ outputDirectory }) => {
    console.log(`Created birthday site: ${outputDirectory}`)
  }).catch((error) => {
    console.error(error.message)
    process.exitCode = 1
  })
}
